#!/bin/bash
/action=PATH. /action
^C
root@4f51d4172012:/alx-system_engineering-devops/0x03-shell_variables_expansions# chmod u+x 2-path
root@4f51d4172012:/alx-system_engineering-devops/0x03-shell_variables_expansions# ls
